INSERT INTO `nationalities`(`id`, `phone`, `code`, `name`, `continent`) VALUES
(1, 213, 'DZ', 'الجزائر', 'Africa'),
(2, 86, 'CN', 'الصين', 'Asia'),
(3, 33, 'FR', 'فرنسا', 'Europe'),
(4, 49, 'DE', 'ألمانيا', 'Europe'),
(5, 39, 'IT', 'إيطاليا', 'Europe'),
(6, 850, 'KP', 'كوريا، الجمهورية الشعبية الديمقراطية', 'Asia'),
(7, 34, 'ES', 'إسبانيا', 'Europe'),
(8, 971, 'AE', 'الإمارات العربية المتحدة', 'Asia'),
(9, 44, 'GB', 'المملكة المتحدة', 'Europe'),
(10, 1, 'US', 'الولايات المتحدة', 'North America')



INSERT INTO `marques`(`id`, `nom`, `noma`) VALUES
(1, 'ACURA', 'Acura'),
(2, 'ALFA', 'Alfa Romeo'),
(3, 'AMC', 'AMC'),
(4, 'ASTON', 'Aston Martin'),
(5, 'AUDI', 'Audi'),
(6, 'AVANTI', 'Avanti'),
(7, 'BENTL', 'Bentley'),
(8, 'BMW', 'BMW'),
(9, 'BUICK', 'Buick'),
(10, 'CAD', 'Cadillac'),
(11, 'CHEV', 'Chevrolet'),
(12, 'CHRY', 'Chrysler'),
(13, 'DAEW', 'Daewoo'),
(14, 'DAIHAT', 'Daihatsu'),
(15, 'DATSUN', 'Datsun'),
(16, 'DELOREAN', 'DeLorean'),
(17, 'DODGE', 'Dodge'),
(18, 'EAGLE', 'Eagle'),
(19, 'FER', 'Ferrari'),
(20, 'FIAT', 'FIAT'),
(21, 'FISK', 'Fisker'),
(22, 'FORD', 'Ford'),
(23, 'FREIGHT', 'Freightliner'),
(24, 'GEO', 'Geo'),
(25, 'GMC', 'GMC'),
(26, 'HONDA', 'Honda'),
(27, 'AMGEN', 'HUMMER'),
(28, 'HYUND', 'Hyundai'),
(29, 'INFIN', 'Infiniti'),
(30, 'ISU', 'Isuzu'),
(31, 'JAG', 'Jaguar'),
(32, 'JEEP', 'Jeep'),
(33, 'KIA', 'Kia'),
(34, 'LAM', 'Lamborghini'),
(35, 'LAN', 'Lancia'),
(36, 'ROV', 'Land Rover'),
(37, 'LEXUS', 'Lexus'),
(38, 'LINC', 'Lincoln'),
(39, 'LOTUS', 'Lotus'),
(40, 'MAS', 'Maserati'),
(41, 'MAYBACH', 'Maybach'),
(42, 'MAZDA', 'Mazda'),
(43, 'MCLAREN', 'McLaren'),
(44, 'MB', 'Mercedes-Benz'),
(45, 'MERC', 'Mercury'),
(46, 'MERKUR', 'Merkur'),
(47, 'MINI', 'MINI'),
(48, 'MIT', 'Mitsubishi'),
(49, 'NISSAN', 'Nissan'),
(50, 'OLDS', 'Oldsmobile'),
(51, 'PEUG', 'Peugeot'),
(52, 'PLYM', 'Plymouth'),
(53, 'PONT', 'Pontiac'),
(54, 'POR', 'Porsche'),
(55, 'RAM', 'RAM'),
(56, 'REN', 'Renault'),
(57, 'RR', 'Rolls-Royce'),
(58, 'SAAB', 'Saab'),
(59, 'SATURN', 'Saturn'),
(60, 'SCION', 'Scion'),
(61, 'SMART', 'smart'),
(62, 'SRT', 'SRT'),
(63, 'STERL', 'Sterling'),
(64, 'SUB', 'Subaru'),
(65, 'SUZUKI', 'Suzuki'),
(66, 'TESLA', 'Tesla'),
(67, 'TOYOTA', 'Toyota'),
(68, 'TRI', 'Triumph'),
(69, 'VOLKS', 'Volkswagen'),
(70, 'VOLVO', 'Volvo'),
(71, 'YUGO', 'Yugo')



INSERT INTO `modeles`(`id`, `marque_id`, `nom`, `noma`) values
(1, 1, 'CL_MODELS', 'CL Models (4)'),
(2, 1, '2.2CL', ' - 2.2CL'),
(3, 1, '2.3CL', ' - 2.3CL'),
(4, 1, '3.0CL', ' - 3.0CL'),
(5, 1, '3.2CL', ' - 3.2CL'),
(25, 2, 'ALFA164', '164'),
(26, 2, 'ALFA8C', '8C Competizione'),
(27, 2, 'ALFAGT', 'GTV-6'),
(28, 2, 'MIL', 'Milano'),
(29, 2, 'SPID', 'Spider'),
(30, 2, 'ALFAOTH', 'Other Alfa Romeo Models'),
(31, 3, 'AMCALLIAN', 'Alliance'),
(32, 3, 'CON', 'Concord'),
(33, 3, 'EAGLE', 'Eagle'),
(34, 3, 'AMCENC', 'Encore'),
(35, 3, 'AMCSPIRIT', 'Spirit');
