+--------+----------------------------------------+---------------------------------------------------+-----------------------------+------------------------------------------------------------------------+------------------------------------------------------------------------------------------------+
| Domain | Method                                 | URI                                               | Name                        | Action                                                                 | Middleware                                                                                     |
+--------+----------------------------------------+---------------------------------------------------+-----------------------------+------------------------------------------------------------------------+------------------------------------------------------------------------------------------------+
|        | GET|HEAD|POST|PUT|PATCH|DELETE|OPTIONS | /                                                 |                             | Illuminate\Routing\RedirectController                                  | web                                                                                            |
|        | GET|HEAD                               | api/user                                          |                             | Closure                                                                | api                                                                                            |
|        |                                        |                                                   |                             |                                                                        | App\Http\Middleware\Authenticate:sanctum                                                       |
|        | GET|HEAD                               | sanctum/csrf-cookie                               |                             | Laravel\Sanctum\Http\Controllers\CsrfCookieController@show             | web                                                                                            |
|        | GET|HEAD                               | {language}                                        |                             | Closure                                                                | web                                                                                            |
|        | POST                                   | {language}/admin/categories                       | admin.categories.store      | App\Http\Controllers\Admin\CategoryController@store                    | web                                                                                            |
|        |                                        |                                                   |                             |                                                                        | App\Http\Middleware\Authenticate                                                               |
|        |                                        |                                                   |                             |                                                                        | App\Http\Middleware\IsAdmin                                                                    |
|        | GET|HEAD                               | {language}/admin/categories                       | admin.categories.index      | App\Http\Controllers\Admin\CategoryController@index                    | web                                                                                            |
|        |                                        |                                                   |                             |                                                                        | App\Http\Middleware\Authenticate                                                               |
|        |                                        |                                                   |                             |                                                                        | App\Http\Middleware\IsAdmin                                                                    |
|        | GET|HEAD                               | {language}/admin/categories/create                | admin.categories.create     | App\Http\Controllers\Admin\CategoryController@create                   | web                                                                                            |
|        |                                        |                                                   |                             |                                                                        | App\Http\Middleware\Authenticate                                                               |
|        |                                        |                                                   |                             |                                                                        | App\Http\Middleware\IsAdmin                                                                    |
|        | DELETE                                 | {language}/admin/categories/{category}            | admin.categories.destroy    | App\Http\Controllers\Admin\CategoryController@destroy                  | web                                                                                            |
|        |                                        |                                                   |                             |                                                                        | App\Http\Middleware\Authenticate                                                               |
|        |                                        |                                                   |                             |                                                                        | App\Http\Middleware\IsAdmin                                                                    |
|        | GET|HEAD                               | {language}/admin/categories/{category}            | admin.categories.show       | App\Http\Controllers\Admin\CategoryController@show                     | web                                                                                            |
|        |                                        |                                                   |                             |                                                                        | App\Http\Middleware\Authenticate                                                               |
|        |                                        |                                                   |                             |                                                                        | App\Http\Middleware\IsAdmin                                                                    |
|        | PUT|PATCH                              | {language}/admin/categories/{category}            | admin.categories.update     | App\Http\Controllers\Admin\CategoryController@update                   | web                                                                                            |
|        |                                        |                                                   |                             |                                                                        | App\Http\Middleware\Authenticate                                                               |
|        |                                        |                                                   |                             |                                                                        | App\Http\Middleware\IsAdmin                                                                    |
|        | GET|HEAD                               | {language}/admin/categories/{category}/edit       | admin.categories.edit       | App\Http\Controllers\Admin\CategoryController@edit                     | web                                                                                            |
|        |                                        |                                                   |                             |                                                                        | App\Http\Middleware\Authenticate                                                               |
|        |                                        |                                                   |                             |                                                                        | App\Http\Middleware\IsAdmin                                                                    |
|        | GET|HEAD                               | {language}/admin/home                             | admin.home                  | Closure                                                                | web                                                                                            |
|        |                                        |                                                   |                             |                                                                        | App\Http\Middleware\Authenticate                                                               |
|        |                                        |                                                   |                             |                                                                        | App\Http\Middleware\IsAdmin                                                                    |
|        | GET|HEAD                               | {language}/admin/marques                          | admin.marques.index         | App\Http\Controllers\Admin\MarqueController@index                      | web                                                                                            |
|        |                                        |                                                   |                             |                                                                        | App\Http\Middleware\Authenticate                                                               |
|        |                                        |                                                   |                             |                                                                        | App\Http\Middleware\IsAdmin                                                                    |
|        | POST                                   | {language}/admin/marques                          | admin.marques.store         | App\Http\Controllers\Admin\MarqueController@store                      | web                                                                                            |
|        |                                        |                                                   |                             |                                                                        | App\Http\Middleware\Authenticate                                                               |
|        |                                        |                                                   |                             |                                                                        | App\Http\Middleware\IsAdmin                                                                    |
|        | GET|HEAD                               | {language}/admin/marques/create                   | admin.marques.create        | App\Http\Controllers\Admin\MarqueController@create                     | web                                                                                            |
|        |                                        |                                                   |                             |                                                                        | App\Http\Middleware\Authenticate                                                               |
|        |                                        |                                                   |                             |                                                                        | App\Http\Middleware\IsAdmin                                                                    |
|        | GET|HEAD                               | {language}/admin/marques/{marque}                 | admin.marques.show          | App\Http\Controllers\Admin\MarqueController@show                       | web                                                                                            |
|        |                                        |                                                   |                             |                                                                        | App\Http\Middleware\Authenticate                                                               |
|        |                                        |                                                   |                             |                                                                        | App\Http\Middleware\IsAdmin                                                                    |
|        | PUT|PATCH                              | {language}/admin/marques/{marque}                 | admin.marques.update        | App\Http\Controllers\Admin\MarqueController@update                     | web                                                                                            |
|        |                                        |                                                   |                             |                                                                        | App\Http\Middleware\Authenticate                                                               |
|        |                                        |                                                   |                             |                                                                        | App\Http\Middleware\IsAdmin                                                                    |
|        | DELETE                                 | {language}/admin/marques/{marque}                 | admin.marques.destroy       | App\Http\Controllers\Admin\MarqueController@destroy                    | web                                                                                            |
|        |                                        |                                                   |                             |                                                                        | App\Http\Middleware\Authenticate                                                               |
|        |                                        |                                                   |                             |                                                                        | App\Http\Middleware\IsAdmin                                                                    |
|        | GET|HEAD                               | {language}/admin/marques/{marque}/edit            | admin.marques.edit          | App\Http\Controllers\Admin\MarqueController@edit                       | web                                                                                            |
|        |                                        |                                                   |                             |                                                                        | App\Http\Middleware\Authenticate                                                               |
|        |                                        |                                                   |                             |                                                                        | App\Http\Middleware\IsAdmin                                                                    |
|        | GET|HEAD                               | {language}/admin/modeles                          | admin.modeles.index         | App\Http\Controllers\Admin\ModeleController@index                      | web                                                                                            |
|        |                                        |                                                   |                             |                                                                        | App\Http\Middleware\Authenticate                                                               |
|        |                                        |                                                   |                             |                                                                        | App\Http\Middleware\IsAdmin                                                                    |
|        | POST                                   | {language}/admin/modeles                          | admin.modeles.store         | App\Http\Controllers\Admin\ModeleController@store                      | web                                                                                            |
|        |                                        |                                                   |                             |                                                                        | App\Http\Middleware\Authenticate                                                               |
|        |                                        |                                                   |                             |                                                                        | App\Http\Middleware\IsAdmin                                                                    |
|        | GET|HEAD                               | {language}/admin/modeles/create                   | admin.modeles.create        | App\Http\Controllers\Admin\ModeleController@create                     | web                                                                                            |
|        |                                        |                                                   |                             |                                                                        | App\Http\Middleware\Authenticate                                                               |
|        |                                        |                                                   |                             |                                                                        | App\Http\Middleware\IsAdmin                                                                    |
|        | GET|HEAD                               | {language}/admin/modeles/{modele}                 | admin.modeles.show          | App\Http\Controllers\Admin\ModeleController@show                       | web                                                                                            |
|        |                                        |                                                   |                             |                                                                        | App\Http\Middleware\Authenticate                                                               |
|        |                                        |                                                   |                             |                                                                        | App\Http\Middleware\IsAdmin                                                                    |
|        | PUT|PATCH                              | {language}/admin/modeles/{modele}                 | admin.modeles.update        | App\Http\Controllers\Admin\ModeleController@update                     | web                                                                                            |
|        |                                        |                                                   |                             |                                                                        | App\Http\Middleware\Authenticate                                                               |
|        |                                        |                                                   |                             |                                                                        | App\Http\Middleware\IsAdmin                                                                    |
|        | DELETE                                 | {language}/admin/modeles/{modele}                 | admin.modeles.destroy       | App\Http\Controllers\Admin\ModeleController@destroy                    | web                                                                                            |
|        |                                        |                                                   |                             |                                                                        | App\Http\Middleware\Authenticate                                                               |
|        |                                        |                                                   |                             |                                                                        | App\Http\Middleware\IsAdmin                                                                    |
|        | GET|HEAD                               | {language}/admin/modeles/{modele}/edit            | admin.modeles.edit          | App\Http\Controllers\Admin\ModeleController@edit                       | web                                                                                            |
|        |                                        |                                                   |                             |                                                                        | App\Http\Middleware\Authenticate                                                               |
|        |                                        |                                                   |                             |                                                                        | App\Http\Middleware\IsAdmin                                                                    |
|        | GET|HEAD                               | {language}/admin/nationalities                    | admin.nationalities.index   | App\Http\Controllers\Admin\NationalityController@index                 | web                                                                                            |
|        |                                        |                                                   |                             |                                                                        | App\Http\Middleware\Authenticate                                                               |
|        |                                        |                                                   |                             |                                                                        | App\Http\Middleware\IsAdmin                                                                    |
|        | POST                                   | {language}/admin/nationalities                    | admin.nationalities.store   | App\Http\Controllers\Admin\NationalityController@store                 | web                                                                                            |
|        |                                        |                                                   |                             |                                                                        | App\Http\Middleware\Authenticate                                                               |
|        |                                        |                                                   |                             |                                                                        | App\Http\Middleware\IsAdmin                                                                    |
|        | GET|HEAD                               | {language}/admin/nationalities/create             | admin.nationalities.create  | App\Http\Controllers\Admin\NationalityController@create                | web                                                                                            |
|        |                                        |                                                   |                             |                                                                        | App\Http\Middleware\Authenticate                                                               |
|        |                                        |                                                   |                             |                                                                        | App\Http\Middleware\IsAdmin                                                                    |
|        | PUT|PATCH                              | {language}/admin/nationalities/{nationality}      | admin.nationalities.update  | App\Http\Controllers\Admin\NationalityController@update                | web                                                                                            |
|        |                                        |                                                   |                             |                                                                        | App\Http\Middleware\Authenticate                                                               |
|        |                                        |                                                   |                             |                                                                        | App\Http\Middleware\IsAdmin                                                                    |
|        | DELETE                                 | {language}/admin/nationalities/{nationality}      | admin.nationalities.destroy | App\Http\Controllers\Admin\NationalityController@destroy               | web                                                                                            |
|        |                                        |                                                   |                             |                                                                        | App\Http\Middleware\Authenticate                                                               |
|        |                                        |                                                   |                             |                                                                        | App\Http\Middleware\IsAdmin                                                                    |
|        | GET|HEAD                               | {language}/admin/nationalities/{nationality}      | admin.nationalities.show    | App\Http\Controllers\Admin\NationalityController@show                  | web                                                                                            |
|        |                                        |                                                   |                             |                                                                        | App\Http\Middleware\Authenticate                                                               |
|        |                                        |                                                   |                             |                                                                        | App\Http\Middleware\IsAdmin                                                                    |
|        | GET|HEAD                               | {language}/admin/nationalities/{nationality}/edit | admin.nationalities.edit    | App\Http\Controllers\Admin\NationalityController@edit                  | web                                                                                            |
|        |                                        |                                                   |                             |                                                                        | App\Http\Middleware\Authenticate                                                               |
|        |                                        |                                                   |                             |                                                                        | App\Http\Middleware\IsAdmin                                                                    |
|        | GET|HEAD                               | {language}/admin/roles                            | admin.roles.index           | App\Http\Controllers\Admin\RoleController@index                        | web                                                                                            |
|        |                                        |                                                   |                             |                                                                        | App\Http\Middleware\Authenticate                                                               |
|        |                                        |                                                   |                             |                                                                        | App\Http\Middleware\IsAdmin                                                                    |
|        |                                        |                                                   |                             |                                                                        | Spatie\Permission\Middlewares\PermissionMiddleware:role-list|role-create|role-edit|role-delete |
|        | POST                                   | {language}/admin/roles                            | admin.roles.store           | App\Http\Controllers\Admin\RoleController@store                        | web                                                                                            |
|        |                                        |                                                   |                             |                                                                        | App\Http\Middleware\Authenticate                                                               |
|        |                                        |                                                   |                             |                                                                        | App\Http\Middleware\IsAdmin                                                                    |
|        |                                        |                                                   |                             |                                                                        | Spatie\Permission\Middlewares\PermissionMiddleware:role-list|role-create|role-edit|role-delete |
|        |                                        |                                                   |                             |                                                                        | Spatie\Permission\Middlewares\PermissionMiddleware:role-create                                 |
|        | GET|HEAD                               | {language}/admin/roles/create                     | admin.roles.create          | App\Http\Controllers\Admin\RoleController@create                       | web                                                                                            |
|        |                                        |                                                   |                             |                                                                        | App\Http\Middleware\Authenticate                                                               |
|        |                                        |                                                   |                             |                                                                        | App\Http\Middleware\IsAdmin                                                                    |
|        |                                        |                                                   |                             |                                                                        | Spatie\Permission\Middlewares\PermissionMiddleware:role-create                                 |
|        | GET|HEAD                               | {language}/admin/roles/{role}                     | admin.roles.show            | App\Http\Controllers\Admin\RoleController@show                         | web                                                                                            |
|        |                                        |                                                   |                             |                                                                        | App\Http\Middleware\Authenticate                                                               |
|        |                                        |                                                   |                             |                                                                        | App\Http\Middleware\IsAdmin                                                                    |
|        | PUT|PATCH                              | {language}/admin/roles/{role}                     | admin.roles.update          | App\Http\Controllers\Admin\RoleController@update                       | web                                                                                            |
|        |                                        |                                                   |                             |                                                                        | App\Http\Middleware\Authenticate                                                               |
|        |                                        |                                                   |                             |                                                                        | App\Http\Middleware\IsAdmin                                                                    |
|        |                                        |                                                   |                             |                                                                        | Spatie\Permission\Middlewares\PermissionMiddleware:role-edit                                   |
|        | DELETE                                 | {language}/admin/roles/{role}                     | admin.roles.destroy         | App\Http\Controllers\Admin\RoleController@destroy                      | web                                                                                            |
|        |                                        |                                                   |                             |                                                                        | App\Http\Middleware\Authenticate                                                               |
|        |                                        |                                                   |                             |                                                                        | App\Http\Middleware\IsAdmin                                                                    |
|        |                                        |                                                   |                             |                                                                        | Spatie\Permission\Middlewares\PermissionMiddleware:role-delete                                 |
|        | GET|HEAD                               | {language}/admin/roles/{role}/edit                | admin.roles.edit            | App\Http\Controllers\Admin\RoleController@edit                         | web                                                                                            |
|        |                                        |                                                   |                             |                                                                        | App\Http\Middleware\Authenticate                                                               |
|        |                                        |                                                   |                             |                                                                        | App\Http\Middleware\IsAdmin                                                                    |
|        |                                        |                                                   |                             |                                                                        | Spatie\Permission\Middlewares\PermissionMiddleware:role-edit                                   |
|        | GET|HEAD                               | {language}/admin/types                            | admin.types.index           | App\Http\Controllers\Admin\TypeController@index                        | web                                                                                            |
|        |                                        |                                                   |                             |                                                                        | App\Http\Middleware\Authenticate                                                               |
|        |                                        |                                                   |                             |                                                                        | App\Http\Middleware\IsAdmin                                                                    |
|        | POST                                   | {language}/admin/types                            | admin.types.store           | App\Http\Controllers\Admin\TypeController@store                        | web                                                                                            |
|        |                                        |                                                   |                             |                                                                        | App\Http\Middleware\Authenticate                                                               |
|        |                                        |                                                   |                             |                                                                        | App\Http\Middleware\IsAdmin                                                                    |
|        | GET|HEAD                               | {language}/admin/types/create                     | admin.types.create          | App\Http\Controllers\Admin\TypeController@create                       | web                                                                                            |
|        |                                        |                                                   |                             |                                                                        | App\Http\Middleware\Authenticate                                                               |
|        |                                        |                                                   |                             |                                                                        | App\Http\Middleware\IsAdmin                                                                    |
|        | GET|HEAD                               | {language}/admin/types/{type}                     | admin.types.show            | App\Http\Controllers\Admin\TypeController@show                         | web                                                                                            |
|        |                                        |                                                   |                             |                                                                        | App\Http\Middleware\Authenticate                                                               |
|        |                                        |                                                   |                             |                                                                        | App\Http\Middleware\IsAdmin                                                                    |
|        | PUT|PATCH                              | {language}/admin/types/{type}                     | admin.types.update          | App\Http\Controllers\Admin\TypeController@update                       | web                                                                                            |
|        |                                        |                                                   |                             |                                                                        | App\Http\Middleware\Authenticate                                                               |
|        |                                        |                                                   |                             |                                                                        | App\Http\Middleware\IsAdmin                                                                    |
|        | DELETE                                 | {language}/admin/types/{type}                     | admin.types.destroy         | App\Http\Controllers\Admin\TypeController@destroy                      | web                                                                                            |
|        |                                        |                                                   |                             |                                                                        | App\Http\Middleware\Authenticate                                                               |
|        |                                        |                                                   |                             |                                                                        | App\Http\Middleware\IsAdmin                                                                    |
|        | GET|HEAD                               | {language}/admin/types/{type}/edit                | admin.types.edit            | App\Http\Controllers\Admin\TypeController@edit                         | web                                                                                            |
|        |                                        |                                                   |                             |                                                                        | App\Http\Middleware\Authenticate                                                               |
|        |                                        |                                                   |                             |                                                                        | App\Http\Middleware\IsAdmin                                                                    |
|        | POST                                   | {language}/admin/users                            | admin.users.store           | App\Http\Controllers\Admin\UserController@store                        | web                                                                                            |
|        |                                        |                                                   |                             |                                                                        | App\Http\Middleware\Authenticate                                                               |
|        |                                        |                                                   |                             |                                                                        | App\Http\Middleware\IsAdmin                                                                    |
|        |                                        |                                                   |                             |                                                                        | Spatie\Permission\Middlewares\PermissionMiddleware:user-list|user-create|user-edit|user-delete |
|        |                                        |                                                   |                             |                                                                        | Spatie\Permission\Middlewares\PermissionMiddleware:user-create                                 |
|        | GET|HEAD                               | {language}/admin/users                            | admin.users.index           | App\Http\Controllers\Admin\UserController@index                        | web                                                                                            |
|        |                                        |                                                   |                             |                                                                        | App\Http\Middleware\Authenticate                                                               |
|        |                                        |                                                   |                             |                                                                        | App\Http\Middleware\IsAdmin                                                                    |
|        |                                        |                                                   |                             |                                                                        | Spatie\Permission\Middlewares\PermissionMiddleware:user-list|user-create|user-edit|user-delete |
|        | GET|HEAD                               | {language}/admin/users/create                     | admin.users.create          | App\Http\Controllers\Admin\UserController@create                       | web                                                                                            |
|        |                                        |                                                   |                             |                                                                        | App\Http\Middleware\Authenticate                                                               |
|        |                                        |                                                   |                             |                                                                        | App\Http\Middleware\IsAdmin                                                                    |
|        |                                        |                                                   |                             |                                                                        | Spatie\Permission\Middlewares\PermissionMiddleware:user-create                                 |
|        | PUT|PATCH                              | {language}/admin/users/{user}                     | admin.users.update          | App\Http\Controllers\Admin\UserController@update                       | web                                                                                            |
|        |                                        |                                                   |                             |                                                                        | App\Http\Middleware\Authenticate                                                               |
|        |                                        |                                                   |                             |                                                                        | App\Http\Middleware\IsAdmin                                                                    |
|        |                                        |                                                   |                             |                                                                        | Spatie\Permission\Middlewares\PermissionMiddleware:user-edit                                   |
|        | GET|HEAD                               | {language}/admin/users/{user}                     | admin.users.show            | App\Http\Controllers\Admin\UserController@show                         | web                                                                                            |
|        |                                        |                                                   |                             |                                                                        | App\Http\Middleware\Authenticate                                                               |
|        |                                        |                                                   |                             |                                                                        | App\Http\Middleware\IsAdmin                                                                    |
|        | DELETE                                 | {language}/admin/users/{user}                     | admin.users.destroy         | App\Http\Controllers\Admin\UserController@destroy                      | web                                                                                            |
|        |                                        |                                                   |                             |                                                                        | App\Http\Middleware\Authenticate                                                               |
|        |                                        |                                                   |                             |                                                                        | App\Http\Middleware\IsAdmin                                                                    |
|        |                                        |                                                   |                             |                                                                        | Spatie\Permission\Middlewares\PermissionMiddleware:user-delete                                 |
|        | GET|HEAD                               | {language}/admin/users/{user}/edit                | admin.users.edit            | App\Http\Controllers\Admin\UserController@edit                         | web                                                                                            |
|        |                                        |                                                   |                             |                                                                        | App\Http\Middleware\Authenticate                                                               |
|        |                                        |                                                   |                             |                                                                        | App\Http\Middleware\IsAdmin                                                                    |
|        |                                        |                                                   |                             |                                                                        | Spatie\Permission\Middlewares\PermissionMiddleware:user-edit                                   |
|        | GET|HEAD                               | {language}/home                                   | home                        | App\Http\Controllers\HomeController@index                              | web                                                                                            |
|        |                                        |                                                   |                             |                                                                        | App\Http\Middleware\Authenticate                                                               |
|        | GET|HEAD                               | {language}/login                                  | login                       | App\Http\Controllers\Auth\LoginController@showLoginForm                | web                                                                                            |
|        |                                        |                                                   |                             |                                                                        | App\Http\Middleware\RedirectIfAuthenticated                                                    |
|        | POST                                   | {language}/login                                  |                             | App\Http\Controllers\Auth\LoginController@login                        | web                                                                                            |
|        |                                        |                                                   |                             |                                                                        | App\Http\Middleware\RedirectIfAuthenticated                                                    |
|        | POST                                   | {language}/logout                                 | logout                      | App\Http\Controllers\Auth\LoginController@logout                       | web                                                                                            |
|        | POST                                   | {language}/password/confirm                       |                             | App\Http\Controllers\Auth\ConfirmPasswordController@confirm            | web                                                                                            |
|        |                                        |                                                   |                             |                                                                        | App\Http\Middleware\Authenticate                                                               |
|        | GET|HEAD                               | {language}/password/confirm                       | password.confirm            | App\Http\Controllers\Auth\ConfirmPasswordController@showConfirmForm    | web                                                                                            |
|        |                                        |                                                   |                             |                                                                        | App\Http\Middleware\Authenticate                                                               |
|        | POST                                   | {language}/password/email                         | password.email              | App\Http\Controllers\Auth\ForgotPasswordController@sendResetLinkEmail  | web                                                                                            |
|        | GET|HEAD                               | {language}/password/reset                         | password.request            | App\Http\Controllers\Auth\ForgotPasswordController@showLinkRequestForm | web                                                                                            |
|        | POST                                   | {language}/password/reset                         | password.update             | App\Http\Controllers\Auth\ResetPasswordController@reset                | web                                                                                            |
|        | GET|HEAD                               | {language}/password/reset/{token}                 | password.reset              | App\Http\Controllers\Auth\ResetPasswordController@showResetForm        | web                                                                                            |
|        | GET|HEAD                               | {language}/register                               | register                    | App\Http\Controllers\Auth\RegisterController@showRegistrationForm      | web                                                                                            |
|        |                                        |                                                   |                             |                                                                        | App\Http\Middleware\RedirectIfAuthenticated                                                    |
|        | POST                                   | {language}/register                               |                             | App\Http\Controllers\Auth\RegisterController@register                  | web                                                                                            |
|        |                                        |                                                   |                             |                                                                        | App\Http\Middleware\RedirectIfAuthenticated                                                    |
|        | GET|HEAD                               | {language}/user/home                              | user.home                   | Closure                                                                | web                                                                                            |
|        |                                        |                                                   |                             |                                                                        | App\Http\Middleware\Authenticate                                                               |
+--------+----------------------------------------+---------------------------------------------------+-----------------------------+------------------------------------------------------------------------+------------------------------------------------------------------------------------------------+
